FROM ruby:2.6.1
MAINTAINER ANASTASIIA

# Set working directory
ENV CURRENT_PATH /usr/src/app
WORKDIR $CURRENT_PATH

# Setting env up
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

# Adding gems
COPY ./Gemfile Gemfile
COPY ./Gemfile.lock Gemfile.lock
RUN bundle install --jobs 20 --retry 5 --without development test
# Adding project files
COPY . .
# RUN bundle exec rake assets:precompile
# EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]